#!/usr/bin/python3
"""
Output format: n=p*q
    one factorization per line
    p and q don’t have to be prime numbers
    See example

You can work on the numbers of the file in the order of your choice
Your program should run without any dependency: You will not be able to install anything on the machine we will run your program on
Time limit: Your program will be killed after 5 seconds if it hasn’t finished
Push all your scripts, source code, etc… to your repository
"""
import sys

def factorize():
    """
    Function to search a file, convert numbers, and format them as n=p*q
    """
    try:
        file_name = sys.argv[1]
        with open(file_name) as f:
            for number in f:
                number = int(number)
                if number % 2 == 0:
                    print("{}={}*{}".format(number, number // 2, 2))
                    continue
                i = 3
                while i < number // 2:
                    if number % i == 0:
                        print("{}={}*{}".format(number, number // i, i))
                        break
                    i += 2
                if i == (number // 2) + 1:
                    print("{}={}*{}".format(number, number, 1))
    except (IndexError):
        pass

# Autostart the factorize function
factorize()
